[general]
disableWidgetRenderWithNgIf = true

[ui]
hideToolbar = true

[global]
menuItems = {} 

[theme]
primaryColor="#FF4B4B"
backgroundColor="D4D0CF"
secondaryBackgroundColor="#0B2E53"
textColor="#333333"
font="sans serif"
